############# Russian navigation ##############

# main menu
[[main]]
name = "Главная"
url = "/"
weight = 1

[[main]]
weight = 2
name = "Борьба с"

[[main]]
parent = "Борьба с"
name = "Дератизация"
url = "/deratization"

[[main]]
parent = "Борьба с"
name = "Дезинфекция"
url = "/disinfection"

[[main]]
parent = "Борьба с"
name = "Постельные клопы"
url = "/bedbugs"

[[main]]
parent = "Борьба с"
name = "Муравьи"
url = "/ants"

[[main]]
parent = "Борьба с"
name = "Тараканы"
url = "/cockroaches"

[[main]]
name = "О нас"
url = "/about"
weight = 3

[[main]]
name = "Контакты"
url = "contacts"
weight = 4