# defaultContentLanguageInSubdir must be true for this to work.

# Other languages redirects
# [[redirects]]
# from = '/fr/**'
# to = '/fr/404.html'
# status = 404

# Default language must be last.
# [[redirects]]
# from = '/**'
# to = '/en/404.html'
# status = 404

# Other languages redirects

[[redirects]]
from = '/lv/**'
to = '/lv/404.html'
status = 404

[[redirects]]
from = '/ru/**'
to = '/ru/404.html'
status = 404

[[redirects]]
from = '/en/**'
to = '/en/404.html'
status = 404

[[redirects]]
from = '**'
to = '/lv/404.html'
status = 404